config/routes.rb
Rails.application.routes.draw do
  resources :classes
  resources :races

end

app/models/classe.rb
class Classe < ActiveRecord::Base
end

app/models/race.rb
class Race < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/classes_controller.rb
class ClassesController < ApplicationController
  before_action :set_class, only: [:show, :edit, :update, :destroy]

  # GET /classes
  # GET /classes.json
  def index
    @classes = Classe.all
  end

  # GET /classes/1
  # GET /classes/1.json
  def show
  end

  # GET /classes/new
  def new
    @class = Classe.new
  end

  # GET /classes/1/edit
  def edit
  end

  # POST /classes
  # POST /classes.json
  def create
    @class = Classe.new(class_params)

    respond_to do |format|
      if @class.save
        format.html { redirect_to @class, notice: 'Classe was successfully created.' }
        format.json { render :show, status: :created, location: @class }
      else
        format.html { render :new }
        format.json { render json: @class.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /classes/1
  # PATCH/PUT /classes/1.json
  def update
    respond_to do |format|
      if @class.update(class_params)
        format.html { redirect_to @class, notice: 'Classe was successfully updated.' }
        format.json { render :show, status: :ok, location: @class }
      else
        format.html { render :edit }
        format.json { render json: @class.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /classes/1
  # DELETE /classes/1.json
  def destroy
    @class.destroy
    respond_to do |format|
      format.html { redirect_to classes_url, notice: 'Classe was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_class
      @class = Classe.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def class_params
      params[:class]
    end
end

app/controllers/races_controller.rb
class RacesController < ApplicationController
  before_action :set_race, only: [:show, :edit, :update, :destroy]

  # GET /races
  # GET /races.json
  def index
    @races = Race.all
  end

  # GET /races/1
  # GET /races/1.json
  def show
  end

  # GET /races/new
  def new
    @race = Race.new
  end

  # GET /races/1/edit
  def edit
  end

  # POST /races
  # POST /races.json
  def create
    @race = Race.new(race_params)

    respond_to do |format|
      if @race.save
        format.html { redirect_to @race, notice: 'Race was successfully created.' }
        format.json { render :show, status: :created, location: @race }
      else
        format.html { render :new }
        format.json { render json: @race.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /races/1
  # PATCH/PUT /races/1.json
  def update
    respond_to do |format|
      if @race.update(race_params)
        format.html { redirect_to @race, notice: 'Race was successfully updated.' }
        format.json { render :show, status: :ok, location: @race }
      else
        format.html { render :edit }
        format.json { render json: @race.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /races/1
  # DELETE /races/1.json
  def destroy
    @race.destroy
    respond_to do |format|
      format.html { redirect_to races_url, notice: 'Race was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_race
      @race = Race.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def race_params
      params[:race]
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/classes_helper.rb
module ClassesHelper
end

app/helpers/races_helper.rb
module RacesHelper
end

app/views/classes/_form.html.slim
= form_for @class do |f|
  - if @class.errors.any?
    #error_explanation
      h2 = "#{pluralize(@class.errors.count, "error")} prohibited this class from being saved:"
      ul
        - @class.errors.full_messages.each do |message|
          li = message

  .actions = f.submit

app/views/classes/edit.html.slim
h1 Editing class

== render 'form'

= link_to 'Show', @class
'|
= link_to 'Back', classes_path

app/views/classes/index.html.slim
h1 Listing classes

table
  thead
    tr
      th
      th
      th

  tbody
    - @classes.each do |class|
      tr
        td = link_to 'Show', class
        td = link_to 'Edit', edit_class_path(class)
        td = link_to 'Destroy', class, data: {:confirm => 'Are you sure?'}, :method => :delete

br

= link_to 'New Classe', new_class_path

app/views/classes/new.html.slim
h1 New class

== render 'form'

= link_to 'Back', classes_path

app/views/classes/show.html.slim
p#notice = notice


= link_to 'Edit', edit_class_path(@class)
'|
= link_to 'Back', classes_path

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | DM35
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  body
    = yield

app/views/races/_form.html.slim
= form_for @race do |f|
  - if @race.errors.any?
    #error_explanation
      h2 = "#{pluralize(@race.errors.count, "error")} prohibited this race from being saved:"
      ul
        - @race.errors.full_messages.each do |message|
          li = message

  .actions = f.submit

app/views/races/edit.html.slim
h1 Editing race

== render 'form'

= link_to 'Show', @race
'|
= link_to 'Back', races_path

app/views/races/index.html.slim
h1 Listing races

table
  thead
    tr
      th
      th
      th

  tbody
    - @races.each do |race|
      tr
        td = link_to 'Show', race
        td = link_to 'Edit', edit_race_path(race)
        td = link_to 'Destroy', race, data: {:confirm => 'Are you sure?'}, :method => :delete

br

= link_to 'New Race', new_race_path

app/views/races/new.html.slim
h1 New race

== render 'form'

= link_to 'Back', races_path

app/views/races/show.html.slim
p#notice = notice


= link_to 'Edit', edit_race_path(@race)
'|
= link_to 'Back', races_path